# Generated by Django 4.2.23 on 2025-07-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display on page (0 first, then 1, etc.)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'role', 'name']},
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='position',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sort order: President=0, VP=1. For others, lower numbers first.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, choices=[('1_lead', 'Lead'), ('2_jt_lead', 'Jt. Lead'), ('3_member', 'Member')], help_text='Role within the department (Lead, Jt. Lead, etc.).', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='student_class',
            field=models.CharField(choices=[('BE', 'BE'), ('TE', 'TE'), ('SE', 'SE')], default='SE', max_length=2),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team_photos/'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Select the department. Leave BLANK for President, VP, Treasurer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department'),
        ),
    ]
