# Generated by Django 4.2.23 on 2025-07-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_delete_event_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='github_link',
            new_name='instagram_link',
        ),
    ]
